# Generated by Django 5.2.1 on 2025-08-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccUsers',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='pass', max_length=100)),
            ],
            options={
                'db_table': 'acc_users',
            },
        ),
    ]
