# Generated by Django 5.2.1 on 2025-08-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tbitemmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineBill',
            fields=[
                ('billno', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('time_field', models.DateTimeField(blank=True, db_column='time', null=True)),
                ('user_field', models.CharField(blank=True, db_column='user', max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
            ],
            options={
                'db_table': 'dine_bill',
            },
        ),
        migrations.CreateModel(
            name='DineKotSalesDetail',
            fields=[
                ('slno', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('billno', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('item', models.CharField(blank=True, max_length=15, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'dine_kot_sales_detail',
            },
        ),
    ]
